// generated by Fast Light User Interface Designer (fluid) version 1.0009

#ifndef ceExtractorConsoleGUI_h
#define ceExtractorConsoleGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <ceExtractorConsoleBase.h>
#include <fltkLightButton.h>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Counter.H>
#include <fltkProgressBar.h>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>

class ceExtractorConsoleGUI : public ceExtractorConsoleBase {
public:
  ceExtractorConsoleGUI();
  Fl_Window *consoleWindow;
  Fl_Group *Connectors;
  Fl_Group *controlsGroup;
  fltk::LightButton *inputButton;
private:
  inline void cb_inputButton_i(fltk::LightButton*, void*);
  static void cb_inputButton(fltk::LightButton*, void*);
public:
  fltk::LightButton *H1xButton;
private:
  inline void cb_H1xButton_i(fltk::LightButton*, void*);
  static void cb_H1xButton(fltk::LightButton*, void*);
  inline void cb_Sigma_i(Fl_Counter*, void*);
  static void cb_Sigma(Fl_Counter*, void*);
public:
  fltk::LightButton *H1yButton;
private:
  inline void cb_H1yButton_i(fltk::LightButton*, void*);
  static void cb_H1yButton(fltk::LightButton*, void*);
public:
  fltk::LightButton *H2xButton;
private:
  inline void cb_H2xButton_i(fltk::LightButton*, void*);
  static void cb_H2xButton(fltk::LightButton*, void*);
public:
  fltk::LightButton *H2yButton;
private:
  inline void cb_H2yButton_i(fltk::LightButton*, void*);
  static void cb_H2yButton(fltk::LightButton*, void*);
public:
  fltk::LightButton *laplacianButton;
private:
  inline void cb_laplacianButton_i(fltk::LightButton*, void*);
  static void cb_laplacianButton(fltk::LightButton*, void*);
public:
  fltk::LightButton *modulusButton;
private:
  inline void cb_modulusButton_i(fltk::LightButton*, void*);
  static void cb_modulusButton(fltk::LightButton*, void*);
public:
  fltk::LightButton *HxButton;
  fltk::LightButton *HyButton;
  fltk::LightButton *HxyButton;
  fltk::LightButton *H2xyButton;
private:
  inline void cb_H2xyButton_i(fltk::LightButton*, void*);
  static void cb_H2xyButton(fltk::LightButton*, void*);
public:
  fltk::ProgressBar *progressSlider;
  Fl_Output *statusTextOutput;
  fltk::LightButton *loadButton;
private:
  inline void cb_loadButton_i(fltk::LightButton*, void*);
  static void cb_loadButton(fltk::LightButton*, void*);
  inline void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
  inline void cb_Execute_i(Fl_Button*, void*);
  static void cb_Execute(Fl_Button*, void*);
public:
  virtual ~ceExtractorConsoleGUI();
  virtual void Quit( void );
  virtual void Load( void );
  virtual void ShowInput( void );
  virtual void ShowFilteredX( void );
  virtual void ShowFilteredY( void );
  virtual void ShowSecondDerivativeX( void );
  virtual void ShowSecondDerivativeY( void );
  virtual void ShowLaplacian( void );
  virtual void ShowGradientModulus( void );
};
#endif
