// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef BacterialColonyGUI_h
#define BacterialColonyGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <Bacteria.h>
#include <FL/Fl_Value_Slider.H>

class BacterialColonyGUI {
public:
  BacterialColonyGUI();
  Fl_Window *panelWindow;
private:
  inline void cb_Division_i(Fl_Value_Slider*, void*);
  static void cb_Division(Fl_Value_Slider*, void*);
  inline void cb_Growth_i(Fl_Value_Slider*, void*);
  static void cb_Growth(Fl_Value_Slider*, void*);
public:
  virtual ~BacterialColonyGUI();
  virtual void Show(void);
  virtual void Hide(void);
};
#endif
