// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "CellsViewerGUI.h"

#include <FL/Fl_Pixmap.H>
static const char *image_itkLogoSmallTransparentBackground[] = {
"100 64 -237 1",
" \300\300\300!111\"999#BBB$JJJ%RRR&ZZZ\'ccc(kkk)sss*{{{+\204\204\204,\214\
\214\214-\224\224\224.\234\234\234/\245\245\245""0\255\255\255""1\265\265\265""\
2\275\275\275""3\306\306\306""4\316\316\316""5\326\326\326""6\336\336\336""7\
\347\347\347""8\357\357\357""9\357\347\347:\326\316\316;\347\336\336<\255\245\
\245=\245\234\224>\224\214\204?\357\347\336@kcZAZRBB\214{JC\204sBD{sZEsc1F1)\
\20G\306\245)HZJ\20I\204k\20J\214\204""cKskJL\234\214JM\214{1N\204s)Osc!P\245\
\214)Q\357\316""9R\336\275""1S\316\255)T\326\265)U\377\326""1V\336\275)W{sJX\
\204s!Y\306\255""1Z\214{![\367\326""9\\\265\234)]\377\336""9^\275\245)_sc\30`\
\367\326""1a{k\30""b\204s\30""c\265\234!d\347\306)e\357\316)f\367\326)g\245\
\214\30h\255\224\30i\224{\bj\214\204Rk\204{Blkc1mcZ!n\224\204)o\234\214)p\275\
\245!q{s9rsk1s\377\347""Bt\377\347""9uRJ\20v\224\204\30w\357\357\347x\367\367\
\357y\377\377\367z\316\316\306{\336\336\326|\347\347\336}\265\265\255~\306\
\306\275\177\224\224\214\200\214\214\204\201ZZR\202RRJ\203\214\214{\204\234\
\234\204\205\204\204k\206))!\207RR9\210RR1\211!!\20\212\20\20\0\213\367\377\
\377\214\336\347\347\215\275\306\306\216\204\214\214\217\20!1\220\357\367\377\
\221\326\336\347\222s{\204\223\20\30!\224\316\336\367\225""9R{\226\245\275\
\347\227""Bc\234\230!9c\231""B\204\377\232\30""9s\233\347\357\377\234\306\326\
\367\235\224\255\336\236Zk\214\237JZ{\240""BRs\241Jc\224\242""BZ\214\243)9Z\
\244""9Z\234\245)Bs\246)R\245\247\20!B\250""9{\377\251)Z\275\252!J\234\253\30""\
9{\254""1s\377\255\20)Z\256)k\357\257\b\30""9\260\0\20""1\261s{\214\262\234\
\265\357\263\214\245\336\264k\214\326\265""c\204\316\266""9R\214\267""Bk\306\
\270""9c\275\271)J\224\272\b\20!\273""9s\357\274!B\214\275""1c\316\276""1k\
\347\277)Z\306\300!J\245\301\30""9\204\302)c\347\303!R\275\304!R\306\305!Z\
\326\306\30""B\245\307\20""1{\310\30J\265\311\20""9\224\312\20""B\255\313\b!Z\
\314\b)s\315\275\316\367\316k{\245\317\224\255\357\320\214\245\347\321{\224\
\326\322s\224\347\323""9Js\324Z{\316\325Rs\306\326!1Z\327""Bc\265\330""1R\245\
\331)J\234\332""1Z\275\333!B\224\334)R\265\335)R\275\336""1k\367\337!J\265\
\340\30""9\214\341\b\30""B\342\b){\343\336\347\377\344\265\306\367\345\214\
\245\357\346s\214\326\347s\224\357\350k\214\347\351""c\204\347\352Rs\316\353Jk\
\306\354""9Z\275\355""1R\255\356\30""9\234\357\20""1\214\360\326\336\367\361Z{\
\347\362\255\275\367\363\245\265\357\364\204\234\357\365\204\234\367\366{\224\
\357\367s\214\347\370!1k\371\316\326\367\372""ck\214\373s\214\357\374k\204\
\347\375\306\316\367\376\275\306\367\377\347\347\357\0\357\357\367\1\367\367\
\377\2\306\306\316\3\316\316\326\4\326\326\336\5\255\255\265\6\275\275\306\7\
\357\357\377\b\275\275\316\t\347\347\377\n\336\336\377\13\0\0\0\f\377\377\377",
"                                     320-++($%%%%$%$%%%%$%*)-.22             \
                       ",
"                                 20,*&&(+/1588x\f\f\f\f\f\f\fxx\0""731.*@%\'*\
.12                               ",
"                              2-(%(-27\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\213""61+&&*/2                            ",
"                           1,&&,4x\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f81)%)/2                         ",
"                        2.\'%-6\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f2*$*0                       ",
"                      2-$)4\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\fx\5&(/2                    ",
"                    2.%,7\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f4(%.3                  ",
"                  3-#,8\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f5(&0                \
 ",
"                 1%*x\f\f8878\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f4$*2              \
 ",
"               2,%5x1,,,,--,-28\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\1\
\343\360\371\375\344\344\363\262\317\364\363\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f.#0              ",
"              1%,8.+\5""6x\fy?{{;0*-x\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\315\351\350\350\350\374\350\374\367\350\350\345\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f7%*2            ",
"             /#45)2\f\f\f\f0\237\271\271\266\222|\f1)5\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\1\371\262\367\367\367\367\322\373\367\367\317\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f,&2           ",
"            .$84)8\f\f\f\f*\356\336\250\250\250\305\245~\f7)5\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\315\367\373\322\367\367\322\350\317\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f1#2          ",
"           ,&xx)8\f\f\f\f.\306\250\250\231\231\250\231\336\323""9\f6)\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\345\350\367\347\367\367\367\317\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f4$1         ",
"          ,\'\f\f00\f\f\f\fx\225\254\250\231\277\331\273\250\250\303-\f\f.2\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\363\350\322\367\367\347\374\317\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f5#2        ",
"         0%\f\f\f,6\f\f\f\fz\246\250\231\246\13\13\217\273\231\256\372\f\f5.\
\f\f\f\f\f\f\213\7\f\f\f\f\f\f\f\f\f\f\f\f\362\350\373\367\322\367\350\317\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f5#2       ",
"        1#x\f\f\f,7\f\f\f\f2\355\250\231\255\13\13\13\277\231\256\236y\f5-\f\
\f\f\f\f\f\262\367\220\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\373\367\367\317\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f3%3      ",
"       3$6\f\f\f\f.2\f\f\f\f:\331\250\231\333\13\13\272\276\231\256\372\f\f00\
\f\f\f\f\f\344\374\322\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\322\367\322\350\
\317\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f.)      ",
"       \'0\f\f\f\f\f\214*\f\f\f\fy\240\336\250\250\331\232\275\231\250\300.\f\
x*8\f\f\f\f\375\350\373\322\7\f\f\f\f\f\f\f\f\f\f\f\362\350\367\373\367\367\
\374\317\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\'/     ",
"      0(\f\f\f\f\f\f\f/-\f\f\f\f<\333\250\231\250\231\231\250\302\240x\f+1\f\
\f\f\f\n\322\367\367\322\220\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\322\373\
\350\317\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f8$2    ",
"     3$7\f\f\f\f\f\f\f\f.+8\f\f\f-\274\302\254\250\336\304\237|8*0\f\f\f\f\
\343\322\350\367\367\366\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\367\367\322\367\
\317\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f.,    ",
"     .+\f\f\f\f\f\f\f\f\f\f3).6\f\f:\261\241\227\236,~.*4\f\f\f\f\343\322\
\367\367\347\367\322\7\f\f\f\f\f\f\f\f\f\f\f\362\350\367\347\367\367\350\317\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f%3   ",
"    3%7\f\f\f\f\f\f\f\f\f\f\f\f2,+,0}=>\200--3\f\f\f\f\f\343\322\367\373\322\
\367\367\322\220\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\367\322\374\317\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f/*   ",
"    0)\f\f\f\f\f\f\f\f\f\f\f\f\f\f\fx7:z:{wy\f\f\f\f\f\f\360\322\367\322\367\
\367\367\367\366\1\f\f\f\f\f\f\f\f\f\f\f\362\350\373\367\322\373\350\317\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\fx#3  ",
"    *3\f\f\f\f\f\f\f\f\f\f\f\f\f\f\213\1\0\360\234\344\226\235\346\263\f\f\f\
\f\376\350\367\373\367\373\322\373\367\322\1\f\f\f\f\f\f\f\f\f\f\f\362\374\
\322\367\367\367\367\317\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f*,3 ",
"   2&x\f\f\f\f\f\f\f\f\f\f\f\220\264\324\353\270\332\332\334\337\337\310\310\
\353\213\f\7\262\374\367\367\322\367\322\367\322\367\322\262\363\363\363\363\
\363\363\262\n\f\f\f\362\350\367\322\373\322\350\317\f\f\f\f\f\f\233\262\262\
\363\363\363\363\363\363\363\363\363\262\262\n\f\f\f\f\f\f\f\f\f\f\f2$4 ",
"   1(\f\f\f\f\f\f\f\f\f\f\f\fx\265\332\303\277\277\251\251\251\335\332\337\
\325\f\f\317\351\350\350\367\367\347\367\367\367\373\367\374\351\351\351\351\
\351\351\361\315\f\f\f\362\350\367\367\367\367\374\317\f\f\f\f\f\f\7\363\366\
\374\350\350\350\350\350\374\351\350\364\262\343\f\f\f\f\f\f\f\f\f\f\f8#3 ",
"   --\f\f\f\f\f\f\f\f\f\f\f\221\203Lk$\230\301\306\337\277\277\277\335\325\f\
\f\360\375\371\371\362\367\367\322\373\322\367\322\315\371\371\371\371\371\
\371\234\0\f\f\f\362\374\322\373\322\367\350\317\f\f\f\f\f\f\f\f\1\345\367\
\367\373\367\350\364\315\233\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f%/3",
"   *\5\f\f\f\f\f\f\f\f\f\f>NS^aGd\\N\207\243\253\252\312\353\213\f\f\f\f\f\
\371\350\367\367\322\367\367\366\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\367\367\
\347\367\317\f\f\f\f\f\f\f\f\f\344\374\347\350\322\344\1\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f(+3",
"   *~\f\f\f\f\f\f\f\f\f\221""aU]S^ssst]d^nl\202-\214\f\f\f\f\371\350\373\322\
\367\373\367\322\220\f\f\f\f\f\f\f\f\f\f\f\362\350\367\322\367\367\350\317\f\f\
\f\f\f\f\f\f\f\317\350\374\317\377\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f+)4",
"   \'4\f\f\f\f\f\f\f\f\f7DjKAm[`ssss]st`pE\215\f\f\f\234\367\367\367\367\322\
\367\322\7\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\373\322\374\317\f\f\f\f\f\f\f\
\1\363\374\367\344\1\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f,(4",
"   \'4\f\f\f\f\f\f\f\f\f\f\1\'mOXqBZG]ss[]sseW\1\f\f\371\350\367\367\347\367\
\367\366\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\373\322\367\350\317\f\f\f\f\f\f\
\343\345\351\364\360\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f+)3",
"   +2\f\f\f\f\f\f\f\f\f\f\f<J\204""17\f\316\260H^]ss[ssM\214\f\f\234\350\373\
\322\367\322\367\322\1\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\367\367\367\317\f\
\f\f\f\f\315\367\374\363\1\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f**3",
"   \222<\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\320\303\357\257""FvR[s]M\221\f\f\
\371\350\367\367\322\373\367\322\7\f\f\f\f\f\f\f\f\f\f\f\362\350\367\322\373\
\322\350\317\f\f\f\220\262\374\322\371\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\',3",
"   /,\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\0\177\242\277\277\277\340\341\223""FY]q\
\0\f\f\371\367\367\347\367\367\373\322\220\f\f\f\f\f\f\f\f\f\f\f\362\350\367\
\367\367\367\374\317\f\f\360\366\374\367\344\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f%/2",
"   1(\f\f\f\f\f\f\f\f\f\f\f\f\f\f\1""Di\370\277\332\332\277\277\335\342PT\
\200\f\f\f\371\350\367\367\367\322\367\322\1\f\f\f\f\f\f\f\f\f\f\f\362\374\
\322\373\322\367\367\317\1\362\350\367\322\367\367\371\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f7#13",
"   3&8\f\f\f\f\f\f\f\f\f\f\f\f\f.cd\370\277\332\335\332\332\277\333_C\377\f\f\
\f\234\350\373\322\367\367\367\366\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\367\
\367\347\367\364\345\350\367\367\373\322\367\367\371\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f/&33",
"    +0\f\f\f\f\f\f\f\f\f\f\f\f\fJe[O\370\310\277\332\332\335\327\5\214\f\f\f\
\f\371\350\367\367\347\367\367\322\7\f\f\f\f\f\f\f\f\f\f\f\362\350\367\322\
\367\367\322\367\374\367\322\367\322\367\373\350\347\360\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f(+23",
"    1\'\f\f\f\f\f\f\f\f\f\f\f\f\f\205RssG\210\370\356\303\304\352\f\f\f\f\f\f\
\371\367\367\322\367\322\373\322\220\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\
\347\367\367\364\364\367\367\347\367\367\322\367\350\367\n\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f7#124",
"     \'5\f\f\f\f\f\f\f\f\f\f\f\f\6X]ss]TN\207\230\244\0\f\f\f\f\f\371\350\
\367\373\322\367\367\322\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\347\367\367\350\
\262\0\364\350\367\367\347\367\322\367\367\322\343\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f+\'323",
"     /(\f\f\f\f\f\f\f\f\f\f\f\f\f.Z[ssst[TnK\3\f\f\f\f\234\350\367\322\367\
\373\367\366\1\f\f\f\f\f\f\f\f\f\f\f\362\374\367\367\322\367\367\317\f\233\
\322\367\322\367\367\373\322\367\350\322\343\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
8\"023 ",
"     3\'3\f\f\f\f\f\f\f\f\f\f\f\f\f\6lhQsssssdr\7\f\f\f\371\350\373\367\322\
\367\367\322\1\f\f\f\f\f\f\f\f\f\f\f\362\350\367\322\373\367\350\317\f\f\233\
\366\367\367\322\367\373\322\367\367\366\233\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f*\
\'314 ",
"      2$\f\f\f\f\f\f\f\f\f\f\f\f\f1\245\341\211ubcVQso3\f\f\f\234\367\322\
\367\373\322\367\322\7\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\367\322\374\317\f\
\f\f\343\366\350\367\367\322\367\367\367\367\322\233\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f4!1233 ",
"       -+\f\f\f\f\f\f\f\f\f\f\f>I\230\275\312\307\313\247\257\206gq\377\f\f\f\
\371\350\367\367\322\367\373\322\t\f\f\f\f\f\f\f\f\f\f\f\362\350\367\373\322\
\367\367\317\f\f\f\f\343\322\367\347\367\322\373\322\367\367\364\7\f\f\f\f\f\f\
\f\f\f\f\f\fx#+314  ",
"       3&1\f\f\f\f\f\f\f\f\f\4Zf\230\275\332\277\275\277\277\274\201\4\f\f\f\
\f\360\367\373\322\367\367\367\367\371\f\f\f\f\f\f\f\f\f\f\f\362\374\322\367\
\367\373\350\317\f\f\f\f\f\360\322\367\367\367\322\367\373\367\350\364\220\f\f\
\f\f\f\f\f\f\f\f\f)&3233  ",
"        2#5\f\f\f\f\f\f\f\f\3oU\243\277\332\332\332\332\335\267\1\f\f\f\f\f\
\233\367\367\373\322\373\322\374\363\f\f\f\f\f\f\f\1\f\f\f\363\350\367\322\
\367\322\367\345\f\f\f\f\f\f\360\367\373\322\367\367\322\367\367\350\345\1\f\f\
\f\f\f\f\f\f\f-\"2213   ",
"         2#6\f\f\f\f\f\f\f\1Wer\311\277\335\335\335\334\334\371\f\f\f\f\f\f\
\317\350\322\367\322\367\367\367\224\f\f\f\f\f\344\364\1\f\1\364\367\367\367\
\373\367\367\367\233\f\f\f\f\f\f\224\367\367\367\347\367\367\322\367\374\345\
\1\f\f\f\f\f\f\f/!0314    ",
"          0#6\f\f\f\f\f\f\f\bHpO\326\334\332\332\332\334\324\220\f\f\f\f\f\
\371\350\367\373\367\367\347\367\322\362\360\343\360\317\351\362\f\213\363\
\350\367\367\347\367\322\373\367\262\1\f\f\f\f\f\f\371\373\367\367\367\322\
\373\322\367\350\345\220\f\f\f\f\f0!03133    ",
"           0#4\f\f\f\f\360\235\324\314\217""F\212\260\355\335\334\335\337\
\353\235\360\f\f\f\f\362\350\367\322\367\367\367\367\350\367\367\374\374\376\
\0\344\364\374\367\367\367\367\367\367\367\367\374\366\362\233\f\f\f\f\f\234\
\367\367\373\367\367\367\367\367\350\322\344\371\213\f.\206""031\6""3     ",
"            1#1\f\f\f\321\337\332\275\354\332\355\330\354\270\270\270\270\
\332\337\346\f\f\f\f\f\315\322\374\350\367\373\367\367\350\374\364\224\f\315\
\374\322\322\366\322\366\322\366\322\366\322\322\322\350\344\f\f\f\f\f\f\234\
\322\322\366\322\366\322\366\322\322\367\365\343*\"13133      ",
"             2$+\f\f\213\1\213\1\1\1\213\213\1\1\1\1\1\1\1\213\f\f\f\f\f\f\7\
\315\262\364\364\322\345\262\234\1\f\f\f\1\f\213\f\f\f\f\f\1\f\f\f\f\1\f\f\f\f\
\f\f\f\f\f\f\f\1\f\f\f\f\f\f6$\202""2213z       ",
"              3\'$5\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\1\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f0!)3\
\6""133        ",
"               3.\206,x\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f6&\"/322\
z3         ",
"                3\6%#1\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\fx\216!)32223\
\6          ",
"                  \2/\"%2\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\fx-\"&032223         \
   ",
"                   ~4,\"%0\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\377,\"%/z22233           \
  ",
"                     33,$#+6\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f3(\"&/\2""21233               ",
"                       33.\'\"&.7\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f4+##*1322233                 ",
"                         342,&\"%,3x\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f\f\f\f\f\f\f\f\f71*$#(/23222333                  ",
"                           3432-\'$#&+05x\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\f\
\f\f\f\f84.*%#%)/23222233                     ",
"                             3334\6""0-(&$#%(+-/135567756421.,*\'$#$\').13322\
22333                       ",
"                                ~333332\5/,)\'\'%%$$##$$$%%&\'(*-012332222333\
3                          ",
"                                   233332333333222122223333322222333333      \
                       ",
"                                        323333333322222223323333322          \
                       "
};
static Fl_Pixmap pixmap_itkLogoSmallTransparentBackground(image_itkLogoSmallTransparentBackground);

inline void CellsViewerGUI::cb_Load_i(Fl_Menu_*, void*) {
  LoadSubstrate();
}
void CellsViewerGUI::cb_Load(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

inline void CellsViewerGUI::cb_Quit_i(Fl_Menu_*, void*) {
  Quit();
}
void CellsViewerGUI::cb_Quit(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

inline void CellsViewerGUI::cb_Cellular_i(Fl_Menu_*, void*) {
  ShowCellularAggregateControls();
}
void CellsViewerGUI::cb_Cellular(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Cellular_i(o,v);
}

inline void CellsViewerGUI::cb_Substrates_i(Fl_Menu_*, void*) {
  substratesWindow->show();
}
void CellsViewerGUI::cb_Substrates(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Substrates_i(o,v);
}

Fl_Menu_Item CellsViewerGUI::menu_[] = {
 {"File", 0,  0, 0, 64, 0, 0, 14, 0},
 {"Load Substrate", 0,  (Fl_Callback*)CellsViewerGUI::cb_Load, 0, 0, 0, 0, 14, 0},
 {"Quit", 0x80071,  (Fl_Callback*)CellsViewerGUI::cb_Quit, 0, 0, 0, 0, 14, 0},
 {0},
 {"View", 0,  0, 0, 64, 0, 0, 14, 0},
 {"Cellular Aggregate Controls", 0,  (Fl_Callback*)CellsViewerGUI::cb_Cellular, 0, 0, 0, 0, 14, 0},
 {"Substrates Controls", 0,  (Fl_Callback*)CellsViewerGUI::cb_Substrates, 0, 0, 0, 0, 14, 0},
 {0},
 {0}
};

inline void CellsViewerGUI::cb_3_i(Fl_Button*, void*) {
  Run();
}
void CellsViewerGUI::cb_3(Fl_Button* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_3_i(o,v);
}

inline void CellsViewerGUI::cb_4square_i(Fl_Button*, void*) {
  Stop();
}
void CellsViewerGUI::cb_4square(Fl_Button* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_4square_i(o,v);
}

inline void CellsViewerGUI::cb__i(Fl_Button*, void*) {
  Restart();
}
void CellsViewerGUI::cb_(Fl_Button* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb__i(o,v);
}

inline void CellsViewerGUI::cb_substratesBrowser_i(Fl_Browser* o, void*) {
  ShowSubstrate( o->text( o->value() ) );
}
void CellsViewerGUI::cb_substratesBrowser(Fl_Browser* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_substratesBrowser_i(o,v);
}

CellsViewerGUI::CellsViewerGUI() {
  Fl_Window* w;
  { Fl_Window* o = controlWindow = new Fl_Window(252, 162, "Control Panel");
    w = o;
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(10, 75, 110, 75);
      o->box(FL_FLAT_BOX);
      pixmap_itkLogoSmallTransparentBackground.label(o);
    }
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 250, 25);
      o->menu(menu_);
    }
    { Fl_Button* o = new Fl_Button(20, 35, 60, 20, "@-3>");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_3);
    }
    { Fl_Button* o = new Fl_Button(80, 35, 60, 20, "@#-4square");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_4square);
    }
    iterationValueOutput = new Fl_Value_Output(180, 66, 60, 25, "Iteration : ");
    numberOfCellsValueOutput = new Fl_Value_Output(180, 93, 60, 25, "Cells : ");
    { Fl_Button* o = new Fl_Button(140, 35, 60, 20, "@#|<");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_);
    }
    timeValueOutput = new Fl_Value_Output(180, 120, 60, 25, "Time : ");
    o->end();
  }
  { Fl_Window* o = substratesWindow = new Fl_Window(249, 146, "Substrates");
    w = o;
    o->user_data((void*)(this));
    { Fl_Browser* o = substratesBrowser = new Fl_Browser(15, 15, 220, 115);
      o->type(1);
      o->callback((Fl_Callback*)cb_substratesBrowser);
    }
    o->end();
  }
}

CellsViewerGUI::~CellsViewerGUI() {
}
