// generated by Fast Light User Interface Designer (fluid) version 1.0009

#include "CellsViewerGUI.h"

#include <FL/Fl_Pixmap.H>
static char *image_itkLogoSmallTransparentBackground[] = {

};
static Fl_Pixmap pixmap_itkLogoSmallTransparentBackground(image_itkLogoSmallTransparentBackground);

inline void CellsViewerGUI::cb_Load_i(Fl_Menu_*, void*) {
  LoadSubstrate();
}
void CellsViewerGUI::cb_Load(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

inline void CellsViewerGUI::cb_Quit_i(Fl_Menu_*, void*) {
  Quit();
}
void CellsViewerGUI::cb_Quit(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

inline void CellsViewerGUI::cb_Cellular_i(Fl_Menu_*, void*) {
  ShowCellularAggregateControls();
}
void CellsViewerGUI::cb_Cellular(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Cellular_i(o,v);
}

inline void CellsViewerGUI::cb_Substrates_i(Fl_Menu_*, void*) {
  substratesWindow->show();
}
void CellsViewerGUI::cb_Substrates(Fl_Menu_* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_Substrates_i(o,v);
}

Fl_Menu_Item CellsViewerGUI::menu_[] = {
 {"File", 0,  0, 0, 64, 0, 0, 14, 0},
 {"Load Substrate", 0,  (Fl_Callback*)CellsViewerGUI::cb_Load, 0, 0, 0, 0, 14, 0},
 {"Quit", 0x80071,  (Fl_Callback*)CellsViewerGUI::cb_Quit, 0, 0, 0, 0, 14, 0},
 {0},
 {"View", 0,  0, 0, 64, 0, 0, 14, 0},
 {"Cellular Aggregate Controls", 0,  (Fl_Callback*)CellsViewerGUI::cb_Cellular, 0, 0, 0, 0, 14, 0},
 {"Substrates Controls", 0,  (Fl_Callback*)CellsViewerGUI::cb_Substrates, 0, 0, 0, 0, 14, 0},
 {0},
 {0}
};

inline void CellsViewerGUI::cb_3_i(Fl_Button*, void*) {
  Run();
}
void CellsViewerGUI::cb_3(Fl_Button* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_3_i(o,v);
}

inline void CellsViewerGUI::cb_4square_i(Fl_Button*, void*) {
  Stop();
}
void CellsViewerGUI::cb_4square(Fl_Button* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_4square_i(o,v);
}

inline void CellsViewerGUI::cb__i(Fl_Button*, void*) {
  Restart();
}
void CellsViewerGUI::cb_(Fl_Button* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb__i(o,v);
}

inline void CellsViewerGUI::cb_substratesBrowser_i(Fl_Browser* o, void*) {
  ShowSubstrate( o->text( o->value() ) );
}
void CellsViewerGUI::cb_substratesBrowser(Fl_Browser* o, void* v) {
  ((CellsViewerGUI*)(o->parent()->user_data()))->cb_substratesBrowser_i(o,v);
}

CellsViewerGUI::CellsViewerGUI() {
  Fl_Window* w;
  { Fl_Window* o = controlWindow = new Fl_Window(252, 162, "Control Panel");
    w = o;
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(10, 75, 110, 75);
      o->box(FL_FLAT_BOX);
      pixmap_itkLogoSmallTransparentBackground.label(o);
    }
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 250, 25);
      o->menu(menu_);
    }
    { Fl_Button* o = new Fl_Button(20, 35, 60, 20, "@-3>");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_3);
    }
    { Fl_Button* o = new Fl_Button(80, 35, 60, 20, "@#-4square");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_4square);
    }
    iterationValueOutput = new Fl_Value_Output(180, 66, 60, 25, "Iteration : ");
    numberOfCellsValueOutput = new Fl_Value_Output(180, 93, 60, 25, "Cells : ");
    { Fl_Button* o = new Fl_Button(140, 35, 60, 20, "@#|<");
      o->labeltype(FL_SYMBOL_LABEL);
      o->callback((Fl_Callback*)cb_);
    }
    timeValueOutput = new Fl_Value_Output(180, 120, 60, 25, "Time : ");
    o->end();
  }
  { Fl_Window* o = substratesWindow = new Fl_Window(249, 146, "Substrates");
    w = o;
    o->user_data((void*)(this));
    { Fl_Browser* o = substratesBrowser = new Fl_Browser(15, 15, 220, 115);
      o->type(1);
      o->callback((Fl_Callback*)cb_substratesBrowser);
    }
    o->end();
  }
}

CellsViewerGUI::~CellsViewerGUI() {
}
