// generated by Fast Light User Interface Designer (fluid) version 1.0009

#include "TissueViewerGUI.h"

inline void TissueViewerGUI::cb_Quit_i(Fl_Menu_*, void*) {
  Quit();
}
void TissueViewerGUI::cb_Quit(Fl_Menu_* o, void* v) {
  ((TissueViewerGUI*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

Fl_Menu_Item TissueViewerGUI::menu_[] = {
 {"File", 0,  0, 0, 64, 0, 0, 14, 0},
 {"Quit", 0x80071,  (Fl_Callback*)TissueViewerGUI::cb_Quit, 0, 0, 0, 0, 14, 0},
 {0},
 {0}
};

TissueViewerGUI::TissueViewerGUI() {
  Fl_Window* w;
  { Fl_Window* o = tissueWindow = new Fl_Window(435, 416, "Tissue Window");
    w = o;
    o->user_data((void*)(this));
    { bio::TissueViewerWindow* o = tissueView = new bio::TissueViewerWindow(5, 5, 425, 405);
      o->box(FL_DOWN_BOX);
      o->color(115);
    }
    o->end();
    o->resizable(o);
  }
  { Fl_Window* o = controlWindow = new Fl_Window(399, 103, "Control Panel");
    w = o;
    o->user_data((void*)(this));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 400, 25);
      o->menu(menu_);
    }
    new Fl_Button(50, 45, 65, 30, ">");
    o->end();
  }
  { Fl_Window* o = new Fl_Window(104, 100);
    w = o;
    o->user_data((void*)(this));
    o->end();
  }
}

TissueViewerGUI::~TissueViewerGUI() {
}

void TissueViewerGUI::Quit(void) {
}

void TissueViewerGUI::Show(void) {
}

void TissueViewerGUI::Hide(void) {
}
