// generated by Fast Light User Interface Designer (fluid) version 1.0009

#ifndef TissueViewerGUI_h
#define TissueViewerGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "TissueViewerWindow.h"
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Button.H>

class TissueViewerGUI {
public:
  TissueViewerGUI();
  Fl_Window *tissueWindow;
  TissueViewerWindow *tissueView;
  Fl_Window *controlWindow;
  static Fl_Menu_Item menu_[];
private:
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
public:
  virtual ~TissueViewerGUI();
  virtual void Quit(void);
  virtual void Show(void);
  virtual void Hide(void);
};
#endif
