// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef liFluoroscopyUnitViewGUI_h
#define liFluoroscopyUnitViewGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liFluoroscopyUnitView.h>

class FluoroscopyUnitViewGUI {
public:
  FluoroscopyUnitViewGUI();
  Fl_Window *ViewWindow;
  li::FluoroscopyUnitView *fluoroscopyUnitViewWindow;
  virtual ~FluoroscopyUnitViewGUI();
  void Show(void);
  void Hide(void);
  fltk::GlWindow * GetWindow(void);
  void SetFluoroscopyImage( const li::FluoroscopyUnitView::ImageType * image );
  fltk::GlWindow::RedrawCommandType::Pointer GetRedrawCommand(void);
};
#endif
