// generated by Fast Light User Interface Designer (fluid) version 1.0010

#include "liOperatingRoomViewGUI.h"

inline void OperatingRoomViewGUI::cb_operatingRoomViewWindow_i(li::OperatingRoomView* o, void*) {
  o->SaveImage();
}
void OperatingRoomViewGUI::cb_operatingRoomViewWindow(li::OperatingRoomView* o, void* v) {
  ((OperatingRoomViewGUI*)(o->parent()->user_data()))->cb_operatingRoomViewWindow_i(o,v);
}

OperatingRoomViewGUI::OperatingRoomViewGUI() {
  Fl_Window* w;
  { Fl_Window* o = ViewWindow = new Fl_Window(490, 460, "Operating Room View");
    w = o;
    o->user_data((void*)(this));
    { li::OperatingRoomView* o = operatingRoomViewWindow = new li::OperatingRoomView(5, 10, 480, 440);
      o->callback((Fl_Callback*)cb_operatingRoomViewWindow);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
}

OperatingRoomViewGUI::~OperatingRoomViewGUI() {
}

void OperatingRoomViewGUI::Show(void) {
  ViewWindow->show();
operatingRoomViewWindow->show();
}

void OperatingRoomViewGUI::Hide(void) {
  ViewWindow->hide();
}

li::OperatingRoomView * OperatingRoomViewGUI::GetWindow(void) {
  return operatingRoomViewWindow;
}

fltk::GlWindowInteractive::RedrawCommandType::Pointer OperatingRoomViewGUI::GetRedrawCommand(void) {
  return operatingRoomViewWindow->GetRedrawCommand();
}
