// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef liOperatingRoomViewGUI_h
#define liOperatingRoomViewGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liOperatingRoomView.h>

class OperatingRoomViewGUI {
public:
  OperatingRoomViewGUI();
  Fl_Window *ViewWindow;
  li::OperatingRoomView *operatingRoomViewWindow;
private:
  inline void cb_operatingRoomViewWindow_i(li::OperatingRoomView*, void*);
  static void cb_operatingRoomViewWindow(li::OperatingRoomView*, void*);
public:
  virtual ~OperatingRoomViewGUI();
  void Show(void);
  void Hide(void);
  li::OperatingRoomView * GetWindow(void);
  fltk::GlWindowInteractive::RedrawCommandType::Pointer GetRedrawCommand(void);
};
#endif
