// generated by Fast Light User Interface Designer (fluid) version 1.0009

#ifndef liSampleGeneratorCollectionGUI_h
#define liSampleGeneratorCollectionGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liSampleGeneratorCollectionBase.h>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Button.H>

class liSampleGeneratorCollectionGUI : public liSampleGeneratorCollectionBase {
public:
  liSampleGeneratorCollectionGUI();
  Fl_Window *controlWindow;
  Fl_Browser *generatorsBrowser;
private:
  inline void cb_generatorsBrowser_i(Fl_Browser*, void*);
  static void cb_generatorsBrowser(Fl_Browser*, void*);
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  virtual ~liSampleGeneratorCollectionGUI();
  virtual void Show(void);
  virtual void Hide(void);
  virtual void ShowSampleGenerator(void);
};
#endif
