// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef liSampleGeneratorPedicleGUI_h
#define liSampleGeneratorPedicleGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liSampleGenerator.h>
#include <FL/Fl_Value_Input.H>

class liSampleGeneratorPedicleGUI : public liSampleGenerator {
public:
  liSampleGeneratorPedicleGUI();
  Fl_Window *parametersWindow;
  Fl_Value_Input *radiusInput;
  Fl_Value_Input *widthInput;
  Fl_Value_Input *falloffInput;
  Fl_Value_Input *thresholdInput;
  virtual ~liSampleGeneratorPedicleGUI();
  virtual double GetRadius(void);
  virtual double GetWidth(void);
  virtual double GetFalloff(void);
  virtual double GetThreshold(void);
};
#endif
