// generated by Fast Light User Interface Designer (fluid) version 1.0010

#include "liSampleGeneratorBodyPlaneGUI.h"

liSampleGeneratorBodyPlaneGUI::liSampleGeneratorBodyPlaneGUI() {
  Fl_Window* w;
  { Fl_Window* o = parametersWindow = new Fl_Window(201, 162, "BodyBottom Parameters");
    w = o;
    o->user_data((void*)(this));
    radiusInput = new Fl_Value_Input(91, 13, 95, 25, "Radius :   ");
    widthInput = new Fl_Value_Input(91, 40, 95, 25, "Width   :   ");
    falloffInput = new Fl_Value_Input(91, 94, 95, 25, "Falloff   :   ");
    thresholdInput = new Fl_Value_Input(91, 121, 95, 25, "Threshold  : ");
    cutArcInput = new Fl_Value_Input(91, 67, 95, 25, "Cut arc   :   ");
    o->end();
  }
}

liSampleGeneratorBodyPlaneGUI::~liSampleGeneratorBodyPlaneGUI() {
}

double liSampleGeneratorBodyPlaneGUI::GetRadius(void) const {
  return radiusInput->value();
}

double liSampleGeneratorBodyPlaneGUI::GetWidth(void) const {
  return widthInput->value();
}

double liSampleGeneratorBodyPlaneGUI::GetCutArc(void) const {
  return cutArcInput->value();
}

double liSampleGeneratorBodyPlaneGUI::GetFalloff(void) const {
  return falloffInput->value();
}

double liSampleGeneratorBodyPlaneGUI::GetThreshold(void) const {
  return thresholdInput->value();
}
