// generated by Fast Light User Interface Designer (fluid) version 1.0010

#include "liSampleGeneratorPedicleGUI.h"

liSampleGeneratorPedicleGUI::liSampleGeneratorPedicleGUI() {
  Fl_Window* w;
  { Fl_Window* o = parametersWindow = new Fl_Window(200, 126, "Pedicle Parameters");
    w = o;
    o->user_data((void*)(this));
    radiusInput = new Fl_Value_Input(94, 11, 95, 25, "Radius :   ");
    widthInput = new Fl_Value_Input(94, 38, 95, 25, "Width   :   ");
    falloffInput = new Fl_Value_Input(94, 65, 95, 25, "Falloff   :   ");
    thresholdInput = new Fl_Value_Input(94, 92, 95, 25, "Threshold  : ");
    o->end();
  }
}

liSampleGeneratorPedicleGUI::~liSampleGeneratorPedicleGUI() {
}

double liSampleGeneratorPedicleGUI::GetRadius(void) {
  return radiusInput->value();
}

double liSampleGeneratorPedicleGUI::GetWidth(void) {
  return widthInput->value();
}

double liSampleGeneratorPedicleGUI::GetFalloff(void) {
  return falloffInput->value();
}

double liSampleGeneratorPedicleGUI::GetThreshold(void) {
  return thresholdInput->value();
}
