// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef liSampleGeneratorGUI_h
#define liSampleGeneratorGUI_h
#include <itkWin32Header.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liSampleGeneratorBase.h>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>

class liSampleGeneratorGUI : public liSampleGeneratorBase {
public:
  liSampleGeneratorGUI();
  Fl_Window *controlWindow;
  Fl_Counter *xSizeCounter;
  Fl_Counter *ySizeCounter;
  Fl_Counter *zSizeCounter;
  Fl_Value_Input *xSpacingInput;
  Fl_Value_Input *ySpacingInput;
  Fl_Value_Input *zSpacingInput;
  Fl_Value_Input *xPositionInput;
  Fl_Value_Input *yPositionInput;
  Fl_Value_Input *zPositionInput;
  Fl_Value_Input *xScaleInput;
  Fl_Value_Input *yScaleInput;
  Fl_Value_Input *zScaleInput;
private:
  inline void cb_Parameters_i(Fl_Button*, void*);
  static void cb_Parameters(Fl_Button*, void*);
public:
  virtual ~liSampleGeneratorGUI();
  virtual void Show(void);
  virtual void Hide(void);
  virtual void ShowParameters(void);
  virtual void SetScaleX(double val);
  virtual void SetScaleY(double val);
  virtual void SetScaleZ(double val);
};
#endif
