// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef liSampleGeneratorBodyPlaneGUI_h
#define liSampleGeneratorBodyPlaneGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liSampleGenerator.h>
#include <FL/Fl_Value_Input.H>

class liSampleGeneratorBodyPlaneGUI : public liSampleGenerator {
public:
  liSampleGeneratorBodyPlaneGUI();
  Fl_Window *parametersWindow;
  Fl_Value_Input *radiusInput;
  Fl_Value_Input *widthInput;
  Fl_Value_Input *falloffInput;
  Fl_Value_Input *thresholdInput;
  Fl_Value_Input *cutArcInput;
  virtual ~liSampleGeneratorBodyPlaneGUI();
  virtual double GetRadius(void) const;
  virtual double GetWidth(void) const;
  virtual double GetCutArc(void) const;
  virtual double GetFalloff(void) const;
  virtual double GetThreshold(void) const;
};
#endif
