// generated by Fast Light User Interface Designer (fluid) version 1.0010

#ifndef liSurgeryTableGUI_h
#define liSurgeryTableGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <liSurgeryTable.h>
#include <FL/Fl_Adjuster.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Button.H>

class SurgeryTableGUI {
  li::SurgeryTable::Pointer m_Table;
public:
  SurgeryTableGUI();
  Fl_Window *controlWindow;
  Fl_Adjuster *heightAdjuster;
private:
  inline void cb_heightAdjuster_i(Fl_Adjuster*, void*);
  static void cb_heightAdjuster(Fl_Adjuster*, void*);
public:
  Fl_Value_Output *heightValueOutput;
  Fl_Adjuster *lateralAdjuster;
private:
  inline void cb_lateralAdjuster_i(Fl_Adjuster*, void*);
  static void cb_lateralAdjuster(Fl_Adjuster*, void*);
public:
  Fl_Value_Output *lateralValueOutput;
  Fl_Adjuster *cranioCaudalAdjuster;
private:
  inline void cb_cranioCaudalAdjuster_i(Fl_Adjuster*, void*);
  static void cb_cranioCaudalAdjuster(Fl_Adjuster*, void*);
public:
  Fl_Value_Output *cranioCaudalValueOutput;
private:
  inline void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
  inline void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
  inline void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
public:
  virtual ~SurgeryTableGUI();
  void Show(void);
  void Hide(void);
  void SetTable( li::SurgeryTable * table);
};
#endif
