/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit
  Module:    TripleTKGUI.h
  Language:  C++
  Date:      $Date$
  Version:   $Revision$

  Copyright (c) 2002 Insight Consortium. All rights reserved.
  See ITKCopyright.txt or http://www.itk.org/HTML/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even 
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
     PURPOSE.  See the above copyright notices for more information.

=========================================================================*/
// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef TripleTKGUI_h
#define TripleTKGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
extern Fl_Window *window;
#include "TripleTK2D.h"
extern TripleTK2D *tk2D;
#include "TripleTK3D.h"
extern TripleTK3D *tk3D;
#include <FL/Fl_Button.H>
extern void upButton_CB(Fl_Button*, void*);
extern void rightButton_CB(Fl_Button*, void*);
extern void leftButton_CB(Fl_Button*, void*);
extern void downButton_CB(Fl_Button*, void*);
extern void buttonExit_CB(Fl_Button*, void*);
extern void resetAll_CB(Fl_Button*, void*);
#include <FL/Fl_Light_Button.H>
extern void allViews_CB(Fl_Light_Button*, void*);
extern Fl_Light_Button *allViewButton;
extern void outline_CB(Fl_Light_Button*, void*);
extern Fl_Light_Button *outlineButton;
#include <FL/Fl_Value_Slider.H>
extern void sliceNumberSlider_CB(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *sliceNumberSlider;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *windowOutput;
extern Fl_Value_Output *levelOutput;
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
extern void axial2D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *axial2D;
extern void sagittal2D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *sagittal2D;
extern void coronal2D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *coronal2D;
extern void levelWindow_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *levelWindowButton;
extern void move2D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *move2DButton;
extern void zoom2D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *zoom2DButton;
extern void sliceScroll_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *sliceViewButton;
extern void axial3D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *axial3D;
extern void sagittal3D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *sagittal3D;
extern void coronal3D_CB(Fl_Check_Button*, void*);
extern Fl_Check_Button *coronal3D;
#include <FL/Fl_Menu_Bar.H>
extern void fileExit_CB(Fl_Menu_*, void*);
Fl_Window* make_window();
extern Fl_Menu_Item menu_[];
#endif
