// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef fltkSlice3DDrawerGUI_h
#define fltkSlice3DDrawerGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <itkObject.h>
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Check_Button.H>

class fltkSlice3DDrawerGUI : public itk::Object {
public:
  fltkSlice3DDrawerGUI();
  Fl_Window *VolumeWindow;
  Fl_Scrollbar *xScrollBar;
private:
  inline void cb_xScrollBar_i(Fl_Scrollbar*, void*);
  static void cb_xScrollBar(Fl_Scrollbar*, void*);
public:
  Fl_Scrollbar *yScrollBar;
private:
  inline void cb_yScrollBar_i(Fl_Scrollbar*, void*);
  static void cb_yScrollBar(Fl_Scrollbar*, void*);
public:
  Fl_Scrollbar *zScrollBar;
private:
  inline void cb_zScrollBar_i(Fl_Scrollbar*, void*);
  static void cb_zScrollBar(Fl_Scrollbar*, void*);
public:
  Fl_Value_Output *xValueOutput;
  Fl_Check_Button *xCheckButton;
private:
  inline void cb_xCheckButton_i(Fl_Check_Button*, void*);
  static void cb_xCheckButton(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *yCheckButton;
private:
  inline void cb_yCheckButton_i(Fl_Check_Button*, void*);
  static void cb_yCheckButton(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *zCheckButton;
private:
  inline void cb_zCheckButton_i(Fl_Check_Button*, void*);
  static void cb_zCheckButton(Fl_Check_Button*, void*);
public:
  Fl_Value_Output *yValueOutput;
  Fl_Value_Output *zValueOutput;
  ~fltkSlice3DDrawerGUI();
  virtual void Show(void);
  virtual void Hide(void);
  virtual void SelectSliceX(void);
  virtual void SelectSliceY(void);
  virtual void SelectSliceZ(void);
  virtual void SetLabel( const char * label );
};
#endif
