// generated by Fast Light User Interface Designer (fluid) version 1.0010

#include "fltkSlice3DDrawerGUI.h"

inline void fltkSlice3DDrawerGUI::cb_xScrollBar_i(Fl_Scrollbar*, void*) {
  SelectSliceX();
}
void fltkSlice3DDrawerGUI::cb_xScrollBar(Fl_Scrollbar* o, void* v) {
  ((fltkSlice3DDrawerGUI*)(o->parent()->user_data()))->cb_xScrollBar_i(o,v);
}

inline void fltkSlice3DDrawerGUI::cb_yScrollBar_i(Fl_Scrollbar*, void*) {
  SelectSliceY();
}
void fltkSlice3DDrawerGUI::cb_yScrollBar(Fl_Scrollbar* o, void* v) {
  ((fltkSlice3DDrawerGUI*)(o->parent()->user_data()))->cb_yScrollBar_i(o,v);
}

inline void fltkSlice3DDrawerGUI::cb_zScrollBar_i(Fl_Scrollbar*, void*) {
  SelectSliceZ();
}
void fltkSlice3DDrawerGUI::cb_zScrollBar(Fl_Scrollbar* o, void* v) {
  ((fltkSlice3DDrawerGUI*)(o->parent()->user_data()))->cb_zScrollBar_i(o,v);
}

inline void fltkSlice3DDrawerGUI::cb_xCheckButton_i(Fl_Check_Button*, void*) {
  SelectSliceX();
SelectSliceX();
}
void fltkSlice3DDrawerGUI::cb_xCheckButton(Fl_Check_Button* o, void* v) {
  ((fltkSlice3DDrawerGUI*)(o->parent()->user_data()))->cb_xCheckButton_i(o,v);
}

inline void fltkSlice3DDrawerGUI::cb_yCheckButton_i(Fl_Check_Button*, void*) {
  SelectSliceY();
SelectSliceY();
}
void fltkSlice3DDrawerGUI::cb_yCheckButton(Fl_Check_Button* o, void* v) {
  ((fltkSlice3DDrawerGUI*)(o->parent()->user_data()))->cb_yCheckButton_i(o,v);
}

inline void fltkSlice3DDrawerGUI::cb_zCheckButton_i(Fl_Check_Button*, void*) {
  SelectSliceZ();
SelectSliceZ();
}
void fltkSlice3DDrawerGUI::cb_zCheckButton(Fl_Check_Button* o, void* v) {
  ((fltkSlice3DDrawerGUI*)(o->parent()->user_data()))->cb_zCheckButton_i(o,v);
}

fltkSlice3DDrawerGUI::fltkSlice3DDrawerGUI() {
  Fl_Window* w;
  { Fl_Window* o = VolumeWindow = new Fl_Window(475, 107, "Data Volume");
    w = o;
    o->user_data((void*)(this));
    { Fl_Scrollbar* o = xScrollBar = new Fl_Scrollbar(35, 23, 345, 20, "X : ");
      o->type(1);
      o->box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_xScrollBar);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Scrollbar* o = yScrollBar = new Fl_Scrollbar(35, 43, 345, 20, "Y : ");
      o->type(1);
      o->box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_yScrollBar);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Scrollbar* o = zScrollBar = new Fl_Scrollbar(35, 63, 345, 20, "Z : ");
      o->type(1);
      o->box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_zScrollBar);
      o->align(FL_ALIGN_LEFT);
    }
    xValueOutput = new Fl_Value_Output(385, 23, 40, 20);
    { Fl_Check_Button* o = xCheckButton = new Fl_Check_Button(425, 18, 30, 30);
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->selection_color(2);
      o->callback((Fl_Callback*)cb_xCheckButton);
      o->align(FL_ALIGN_CENTER);
    }
    { Fl_Check_Button* o = yCheckButton = new Fl_Check_Button(425, 38, 30, 30);
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->selection_color(2);
      o->callback((Fl_Callback*)cb_yCheckButton);
      o->align(FL_ALIGN_CENTER);
    }
    { Fl_Check_Button* o = zCheckButton = new Fl_Check_Button(425, 58, 30, 30);
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->selection_color(2);
      o->callback((Fl_Callback*)cb_zCheckButton);
      o->align(FL_ALIGN_CENTER);
    }
    yValueOutput = new Fl_Value_Output(385, 43, 40, 20);
    zValueOutput = new Fl_Value_Output(385, 63, 40, 20);
    o->end();
  }
}

fltkSlice3DDrawerGUI::~fltkSlice3DDrawerGUI() {
}

void fltkSlice3DDrawerGUI::Show(void) {
}

void fltkSlice3DDrawerGUI::Hide(void) {
}

void fltkSlice3DDrawerGUI::SelectSliceX(void) {
}

void fltkSlice3DDrawerGUI::SelectSliceY(void) {
}

void fltkSlice3DDrawerGUI::SelectSliceZ(void) {
}
