// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "fltkSlice2DDrawerGUI.h"

inline void fltkSlice2DDrawerGUI::cb_enableCheckButton_i(Fl_Check_Button* o, void*) {
  SetEnabled( (o->value()==1) ? true : false );
}
void fltkSlice2DDrawerGUI::cb_enableCheckButton(Fl_Check_Button* o, void* v) {
  ((fltkSlice2DDrawerGUI*)(o->parent()->user_data()))->cb_enableCheckButton_i(o,v);
}

fltkSlice2DDrawerGUI::fltkSlice2DDrawerGUI() {
  Fl_Window* w;
  { Fl_Window* o = VolumeWindow = new Fl_Window(279, 100, "Image Display Control");
    w = o;
    o->user_data((void*)(this));
    { Fl_Check_Button* o = enableCheckButton = new Fl_Check_Button(70, 30, 120, 25, "Make Visible");
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->selection_color(2);
      o->callback((Fl_Callback*)cb_enableCheckButton);
      o->align(FL_ALIGN_CENTER);
    }
    o->end();
  }
}

fltkSlice2DDrawerGUI::~fltkSlice2DDrawerGUI() {
}

void fltkSlice2DDrawerGUI::Show(void) {
}

void fltkSlice2DDrawerGUI::Hide(void) {
}

void fltkSlice2DDrawerGUI::SetEnabled(bool) {
}

void fltkSlice2DDrawerGUI::SetLabel( const char * label ) {
  VolumeWindow->label( label );
}
