// generated by Fast Light User Interface Designer (fluid) version 1.0009

#ifndef fltkDisplayGlWindowFlatGUI_h
#define fltkDisplayGlWindowFlatGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <fltkGlWindowInteractiveFlat.h>
#include <fltkDrawer.h>

class fltkDisplayGlWindowFlatGUI {
public:
  fltkDisplayGlWindowFlatGUI();
private:
  Fl_Window *parentWindow;
  fltk::GlWindowInteractiveFlat *drawWindow;
public:
  void Show(void);
  void SetLabel(const char *newlabel);
  void Redraw(void);
  void Size(unsigned int nx, unsigned int ny);
  void Hide(void);
  void Update(void);
  int GetWidth(void);
  int GetHeight(void);
  void MakeCurrent(void);
  int IsVisible(void);
  itk::Command::Pointer GetRedrawCommand(void);
  itk::Object::Pointer GetNotifier(void);
  virtual void SetBackground(GLfloat r, GLfloat g, GLfloat b);
};
#endif
