// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef fltkSlice2DDrawerGUI_h
#define fltkSlice2DDrawerGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <itkObject.h>
#include <FL/Fl_Check_Button.H>

class fltkSlice2DDrawerGUI : public itk::Object {
public:
  fltkSlice2DDrawerGUI();
  Fl_Window *VolumeWindow;
  Fl_Check_Button *enableCheckButton;
private:
  inline void cb_enableCheckButton_i(Fl_Check_Button*, void*);
  static void cb_enableCheckButton(Fl_Check_Button*, void*);
public:
  ~fltkSlice2DDrawerGUI();
  virtual void Show(void);
  virtual void Hide(void);
  virtual void SetEnabled(bool);
  virtual void SetLabel( const char * label );
};
#endif
