// generated by Fast Light User Interface Designer (fluid) version 1.0009

#ifndef fltkImage2DViewerGUI_h
#define fltkImage2DViewerGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <fltkImage2DViewerWindow.h>

class fltkImage2DViewerGUI {
public:
  fltkImage2DViewerGUI();
  Fl_Window *externalWindow;
  fltk::Image2DViewerWindow *imageViewer;
  ~fltkImage2DViewerGUI();
  void SetLabel(const char *label);
  void Show(void);
  void Hide(void);
  void Redraw(void);
};
#endif
