// generated by Fast Light User Interface Designer (fluid) version 1.0009

#include "fltkImage2DViewerGUI.h"

fltkImage2DViewerGUI::fltkImage2DViewerGUI() {
  Fl_Window* w;
  { Fl_Window* o = externalWindow = new Fl_Window(454, 367);
    w = o;
    o->user_data((void*)(this));
    imageViewer = new fltk::Image2DViewerWindow(0, 0, 450, 365);
    o->end();
  }
}

fltkImage2DViewerGUI::~fltkImage2DViewerGUI() {
}

void fltkImage2DViewerGUI::SetLabel(const char *label) {
  externalWindow->label( label );
}

void fltkImage2DViewerGUI::Show(void) {
  externalWindow->show();
imageViewer->show();
}

void fltkImage2DViewerGUI::Hide(void) {
  externalWindow->hide();
}

void fltkImage2DViewerGUI::Redraw(void) {
  imageViewer->redraw();
Fl::check();
}
